In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
L = [15,
14.75,
14.5,
14.25,
14,
13.75,
13.5,
13.25,
13,
12.75,
12.5,
12.25,
12,
11.75,
11.5,
11]
d1 = np.array(L)
M = [5,
5,
5,
4.96,
4.28,
2.18,
0.454,
0.042, 
0.011,
0.011,
0.011,
0.011,
0.008,
0.008,
0.007,
0.007]
p1 = np.array(M)
norm1 = p1/5
sno =np.array( [i for i in range(1,len(M)+1)])
t1 = {"S.No":sno, "Position of Knife(mm)":d1, "Power Meter Reading(mW)":p1, "Noramlized Power meter reading":norm1}
pd.DataFrame(t1)

,S.No,Position of Knife(mm),Power Meter Reading(mW),Noramlized Power meter reading
0,1,15.00,5.000,1.0000
1,2,14.75,5.000,1.0000
2,3,14.50,5.000,1.0000
3,4,14.25,4.960,0.9920
4,5,14.00,4.280,0.8560
5,6,13.75,2.180,0.4360
6,7,13.50,0.454,0.0908
7,8,13.25,0.042,0.0084
8,9,13.00,0.011,0.0022
9,10,12.75,0.011,0.0022
10,11,12.50,0.011,0.0022
11,12,12.25,0.011,0.0022
12,13,12.00,0.008,0.0016
13,14,11.75,0.008,0.0016
14,15,11.50,0.007,0.0014
15,16,11.00,0.007,0.0014

In [23]:
L = []
p = 11
while p>9:
    L.append(p)
    p-=0.1
d1 = np.array(L)
M = [6.47,6.45,6.37,6.2,5.84,5.33,4.47,3.39,2.3,1.38,0.784,0.351,0.135,0.052,0.029,0.015,0.012,0.010,0.010,0.010,0.010]
p1 = np.array(M)
norm1 = p1/6.47
sno =np.array( [i for i in range(1,len(M)+1)])
t1 = {"S.No":sno, "Position of Knife(mm)":d1, "Power Meter Reading(mW)":p1, "Noramlized Power meter reading":norm1}
pd.DataFrame(t1)

,S.No,Position of Knife(mm),Power Meter Reading(mW),Noramlized Power meter reading
0,1,11.0,6.470,1.000000
1,2,10.9,6.450,0.996909
2,3,10.8,6.370,0.984544
3,4,10.7,6.200,0.958269
4,5,10.6,5.840,0.902628
5,6,10.5,5.330,0.823802
6,7,10.4,4.470,0.690881
7,8,10.3,3.390,0.523957
8,9,10.2,2.300,0.355487
9,10,10.1,1.380,0.213292
10,11,10.0,0.784,0.121175
11,12,9.9,0.351,0.054250
12,13,9.8,0.135,0.020866
13,14,9.7,0.052,0.008037
14,15,9.6,0.029,0.004482
15,16,9.5,0.015,0.002318
16,17,9.4,0.012,0.001855
17,18,9.3,0.010,0.001546
18,19,9.2,0.010,0.001546
19,20,9.1,0.010,0.001546
20,21,9.0,0.010,0.001546

In [15]:
L = []
p = 11
while p>9:
    L.append(p)
    p-=0.1
d1 = np.array(L)
M = [6.48,6.47,6.45,6.37,6.2,5.84,5.33,4.47,3.39,2.3,1.38,0.784,0.351,0.135,0.052,0.029,0.015,0.012,0.010,0.010,0.010,0.010]
p1 = np.array(M)

In [17]:
d1

array([11. , 10.9, 10.8, 10.7, 10.6, 10.5, 10.4, 10.3, 10.2, 10.1, 10. ,
        9.9,  9.8,  9.7,  9.6,  9.5,  9.4,  9.3,  9.2,  9.1,  9. ])

In [18]:
M

[6.48,
 6.47,
 6.45,
 6.37,
 6.2,
 5.84,
 5.33,
 4.47,
 3.39,
 2.3,
 1.38,
 0.784,
 0.351,
 0.135,
 0.052,
 0.029,
 0.015,
 0.012,
 0.01,
 0.01,
 0.01,
 0.01]

In [19]:
len(M)

22

In [20]:
len(d1)

21

In [31]:
L = []
p = 16
while p>13.5:
    L.append(p)
    p-=0.1
d1 = np.array(L)
M = [5.01,5.00,5.00,4.99,4.97,4.89,4.71,4.37,3.78,3.00,2.16,1.38,0.740,0.318,0.123,0.045,0.018,0.008,0.005,0.003,0.003,0.002,0.001,0.001,0.001,0.001]
p1 = np.array(M)
norm1 = p1/5.01
sno =np.array( [i for i in range(1,len(M)+1)])
t1 = {"S.No":sno, "Position of Knife(mm)":d1, "Power Meter Reading(mW)":p1, "Noramlized Power meter reading":norm1}
pd.DataFrame(t1)

,S.No,Position of Knife(mm),Power Meter Reading(mW),Noramlized Power meter reading
0,1,16.0,5.010,1.000000
1,2,15.9,5.000,0.998004
2,3,15.8,5.000,0.998004
3,4,15.7,4.990,0.996008
4,5,15.6,4.970,0.992016
5,6,15.5,4.890,0.976048
6,7,15.4,4.710,0.940120
7,8,15.3,4.370,0.872255
8,9,15.2,3.780,0.754491
9,10,15.1,3.000,0.598802
10,11,15.0,2.160,0.431138
11,12,14.9,1.380,0.275449
12,13,14.8,0.740,0.147705
13,14,14.7,0.318,0.063473
14,15,14.6,0.123,0.024551
15,16,14.5,0.045,0.008982
16,17,14.4,0.018,0.003593
17,18,14.3,0.008,0.001597
18,19,14.2,0.005,0.000998
19,20,14.1,0.003,0.000599
20,21,14.0,0.003,0.000599
21,22,13.9,0.002,0.000399
22,23,13.8,0.001,0.000200
23,24,13.7,0.001,0.000200
24,25,13.6,0.001,0.000200
25,26,13.5,0.001,0.000200

True